api = "0.2"

[buildpack]
id = "paketo-buildpacks/npm-install"
name = "Paketo NPM Install Buildpack"
homepage = "https://github.com/paketo-buildpacks/npm-install"

[metadata]
include_files = [ "bin/build", "bin/detect", "bin/run", "buildpack.toml" ]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
