api = "0.2"

[buildpack]
id = "paketo-buildpacks/npm"
name = "NPM Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/npm"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
